--- #YAML:1.0
name:               POSIX-1003
version:            0.11
abstract:           POSIX::1003, alternative for POSIX in core
author:
    - Mark Overmeer
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Errno:       0
    Fcntl:       0
    File::Spec:  0
    POSIX:       0
    Test::More:  0.47
    XSLoader:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
